### ISSUE TITLE
Automatically Merge/Match Common Dupes

### ISSUE THREAD

**Issue by macmanx2** [Clorith/WP-IRC-Contributors#2]
IRC is fun, until it randomly feels like changing your "nickname" to "nickname_" or even "nickname__"

Perhaps, in order to ensure optimal ContriBotting, _ should be stripped when it is the last character in the nickname.

**Comment by Clorith** [comment]
The possibly related nicknames code implemented in 8c7fa18dc8a5530c122b0421b555d80b367b89de takes care of this.

Merges are still a manual process as it is possible with false positives (especially in cases with dynamic IPs), but at least this helps us identify the potential matches to look into it easily.

For example http://contribot.clorith.net/details.php?nickname=sterndata is a quick fix at this point.
